language: generic
sudo: required
services:
    - docker

before-install:
    - docker build -t abhijitmazumdar/docker-react -f Dockerfile.dev

script:
    - docker run -e CI=true abhijitmazumdar/docker-react npm run test